---
- name: Генерування файлу конфігурації для Alcatel Omni Switch 6850-U24X
  template: src=alcatel-os-6850-u24x.j2 dest=/tmp/configs/alcatel-os-6850-u24x-{{ item.hostname }}.txt
  with_items: "{{ switches }}"
